language: python

python:
  - "3.6"

sudo: false

cache: pip
install:
  - pip install -r requirements.txt

script: "make html"

deploy:
  provider: pages
  local-dir: build/html/
  skip-cleanup: true
  github-token: $DOC_COCALC_TOKEN
  keep-history: false
  fqdn: doc.cocalc.com
  target-branch: gh-pages
  on:
    branch: master
